// Menu database module for Maestro Kitchen POS
export const DEFAULT_MENU = [
  // CHINESE SOUPS
  { id: "soup-hot-sour-veg", name: "Hot & Sour Soup (Veg)", category: "Chinese Soups", price: 125, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "soup-hot-sour-nonveg", name: "Hot & Sour Soup (Non-Veg)", category: "Chinese Soups", price: 135, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "soup-manchow-veg", name: "Manchow Soup (Veg)", category: "Chinese Soups", price: 125, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "soup-manchow-nonveg", name: "Manchow Soup (Non-Veg)", category: "Chinese Soups", price: 135, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "soup-lemon-coriander-veg", name: "Lemon Coriander Soup (Veg)", category: "Chinese Soups", price: 125, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "soup-lemon-coriander-nonveg", name: "Lemon Coriander Soup (Non-Veg)", category: "Chinese Soups", price: 135, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "soup-clear-veg", name: "Clear Soup (Veg)", category: "Chinese Soups", price: 125, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "soup-clear-nonveg", name: "Clear Soup (Non-Veg)", category: "Chinese Soups", price: 109, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "soup-sweet-corn-veg", name: "Sweet Corn Soup (Veg)", category: "Chinese Soups", price: 135, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "soup-sweet-corn-nonveg", name: "Sweet Corn Soup (Non-Veg)", category: "Chinese Soups", price: 149, isVeg: false, available: true, discountPercent: 0, image: "" },

  // VEG STARTERS
  { id: "starter-veg-manchuria", name: "Veg Manchuria", category: "Veg Starters", price: 135, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-gobi-manchuria", name: "Gobi Manchuria", category: "Veg Starters", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-gobi-65", name: "Gobi 65", category: "Veg Starters", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-gobi-chilly", name: "Gobi Chilly", category: "Veg Starters", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-mushroom-manchuria", name: "Mushroom Manchuria", category: "Veg Starters", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-mushroom-65", name: "Mushroom 65", category: "Veg Starters", price: 179, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-mushroom-chilly", name: "Mushroom Chilly", category: "Veg Starters", price: 179, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-baby-corn-manchuria", name: "Baby Corn Manchuria", category: "Veg Starters", price: 179, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-baby-corn-65", name: "Baby Corn 65", category: "Veg Starters", price: 189, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-baby-corn-chilly", name: "Baby Corn Chilly", category: "Veg Starters", price: 189, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-crispy-corn", name: "Crispy Corn", category: "Veg Starters", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-corn-salt-pepper", name: "Corn Salt & Pepper", category: "Veg Starters", price: 149, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-veg-kaju-manchuria", name: "Veg Kaju Manchuria", category: "Veg Starters", price: 215, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-paneer-manchuria", name: "Paneer Manchuria", category: "Veg Starters", price: 189, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-paneer-65", name: "Paneer 65", category: "Veg Starters", price: 199, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-paneer-chilly", name: "Paneer Chilly", category: "Veg Starters", price: 199, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "starter-kaju-paneer-manchuria", name: "Kaju Paneer Manchuria", category: "Veg Starters", price: 215, isVeg: true, available: true, discountPercent: 0, image: "" },

  // NON-VEG STARTERS
  { id: "starter-egg-omlet", name: "Egg Omlet", category: "Non-Veg Starters", price: 89, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-egg-manchuria", name: "Egg Manchuria", category: "Non-Veg Starters", price: 155, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-egg-chilly", name: "Egg Chilly", category: "Non-Veg Starters", price: 169, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-egg-65", name: "Egg 65", category: "Non-Veg Starters", price: 169, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-chicken-manchuria", name: "Chicken Manchuria", category: "Non-Veg Starters", price: 205, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-chicken-65", name: "Chicken 65", category: "Non-Veg Starters", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-garlic-chicken", name: "Garlic Chicken", category: "Non-Veg Starters", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-pepper-chicken", name: "Pepper Chicken", category: "Non-Veg Starters", price: 229, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-chilly-chicken", name: "Chilly Chicken", category: "Non-Veg Starters", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-chicken-lollypop", name: "Chicken Lollypop", category: "Non-Veg Starters", price: 229, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-chicken-majestic", name: "Chicken Majestic", category: "Non-Veg Starters", price: 239, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-chicken-555", name: "Chicken 555", category: "Non-Veg Starters", price: 249, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-dragon-chicken", name: "Dragon Chicken", category: "Non-Veg Starters", price: 249, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-royal-chicken", name: "Royal Chicken", category: "Non-Veg Starters", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-kaju-nut-chicken", name: "Kaju Nut Chicken", category: "Non-Veg Starters", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-chilly-fish", name: "Chilly Fish", category: "Non-Veg Starters", price: 275, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-apollo-fish", name: "Apollo Fish", category: "Non-Veg Starters", price: 275, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-prawns-manchuria", name: "Prawns Manchuria", category: "Non-Veg Starters", price: 259, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-prawns-chilly", name: "Prawns Chilly", category: "Non-Veg Starters", price: 269, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-pepper-prawns", name: "Pepper Prawns", category: "Non-Veg Starters", price: 335, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-loose-prawns", name: "Loose Prawns", category: "Non-Veg Starters", price: 335, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "starter-golden-fry-prawns", name: "Golden Fry Prawns", category: "Non-Veg Starters", price: 279, isVeg: false, available: true, discountPercent: 0, image: "" },

  // VEG RICE
  { id: "rice-veg-fried", name: "Veg Fried Rice", category: "Veg Rice", price: 99, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-veg-schezwan-fried", name: "Veg Schezwan Fried Rice", category: "Veg Rice", price: 119, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-veg-manchurian", name: "Veg Manchurian Rice", category: "Veg Rice", price: 119, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-veg-manchurian-schezwan", name: "Veg Manchurian Schezwan Rice", category: "Veg Rice", price: 139, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-gobi-fried", name: "Gobi Fried Rice", category: "Veg Rice", price: 109, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-gobi-schezwan-fried", name: "Gobi Schezwan Fried Rice", category: "Veg Rice", price: 129, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-mushroom-fried", name: "Mushroom Fried Rice", category: "Veg Rice", price: 119, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-mushroom-schezwan", name: "Mushroom Schezwan Rice", category: "Veg Rice", price: 129, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-paneer-fried", name: "Paneer Fried Rice", category: "Veg Rice", price: 139, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-paneer-schezwan", name: "Paneer Schezwan Rice", category: "Veg Rice", price: 149, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-corn", name: "Corn Rice", category: "Veg Rice", price: 109, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rice-jeera", name: "Jeera Rice", category: "Veg Rice", price: 109, isVeg: true, available: true, discountPercent: 0, image: "" },

  // VEG NOODLES
  { id: "noodles-veg", name: "Veg Noodles", category: "Veg Noodles", price: 109, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "noodles-veg-schezwan", name: "Veg Schezwan Noodles", category: "Veg Noodles", price: 119, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "noodles-veg-manchurian", name: "Veg Manchurian Noodles", category: "Veg Noodles", price: 129, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "noodles-veg-manchurian-schezwan", name: "Veg Manchuria Schezwan Noodles", category: "Veg Noodles", price: 139, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "noodles-haka", name: "Haka Noodles", category: "Veg Noodles", price: 139, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "noodles-paneer", name: "Paneer Noodles", category: "Veg Noodles", price: 139, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "noodles-paneer-schezwan", name: "Paneer Schezwan Noodles", category: "Veg Noodles", price: 149, isVeg: true, available: true, discountPercent: 0, image: "" },

  // NON-VEG RICE
  { id: "rice-egg-fried", name: "Egg Fried Rice", category: "Non-Veg Rice", price: 119, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "rice-egg-schezwan", name: "Egg Schezwan Rice", category: "Non-Veg Rice", price: 129, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "rice-chicken-fried", name: "Chicken Fried Rice", category: "Non-Veg Rice", price: 139, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "rice-chicken-schezwan", name: "Chicken Schezwan Rice", category: "Non-Veg Rice", price: 149, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "rice-chilly-garlic-chicken", name: "Chilly Garlic Chicken Rice", category: "Non-Veg Rice", price: 149, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "rice-chilly-garlic-egg", name: "Chilly Garlic Egg Rice", category: "Non-Veg Rice", price: 139, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "rice-prawns-fried", name: "Prawns Fried Rice", category: "Non-Veg Rice", price: 179, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "rice-prawns-schezwan", name: "Prawns Schezwan Rice", category: "Non-Veg Rice", price: 189, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "rice-mix-nonveg-fried", name: "Mix Non-Veg Fried Rice", category: "Non-Veg Rice", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "rice-mix-nonveg-schezwan", name: "Mix Non-Veg Schezwan Rice", category: "Non-Veg Rice", price: 239, isVeg: false, available: true, discountPercent: 0, image: "" },

  // NON-VEG NOODLES
  { id: "noodles-egg", name: "Egg Noodles", category: "Non-Veg Noodles", price: 119, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "noodles-egg-schezwan", name: "Egg Schezwan Noodles", category: "Non-Veg Noodles", price: 129, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "noodles-chicken", name: "Chicken Noodles", category: "Non-Veg Noodles", price: 139, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "noodles-chicken-schezwan", name: "Chicken Schezwan Noodles", category: "Non-Veg Noodles", price: 149, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "noodles-chilly-garlic-chicken", name: "Chilly Garlic Chicken Noodles", category: "Non-Veg Noodles", price: 149, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "noodles-chilly-garlic-egg", name: "Chilly Garlic Egg Noodles", category: "Non-Veg Noodles", price: 139, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "noodles-prawns", name: "Prawns Noodles", category: "Non-Veg Noodles", price: 169, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "noodles-prawns-schezwan", name: "Schezwan Prawns Noodles", category: "Non-Veg Noodles", price: 189, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "noodles-mix-nonveg", name: "Mix Non-Veg Noodles", category: "Non-Veg Noodles", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "noodles-mix-nonveg-schezwan", name: "Schezwan Mix Non-Veg Noodles", category: "Non-Veg Noodles", price: 239, isVeg: false, available: true, discountPercent: 0, image: "" },

  // BIRYANI (SINGLE / FULL)
  { id: "biryani-chicken-dum-single", name: "Chicken Dum Biryani (Single)", category: "Biryani", price: 169, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-dum-full", name: "Chicken Dum Biryani (Full)", category: "Biryani", price: 275, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-fry-single", name: "Chicken Fry Piece Biryani (Single)", category: "Biryani", price: 185, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-fry-full", name: "Chicken Fry Piece Biryani (Full)", category: "Biryani", price: 285, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-special-single", name: "Special Chicken Biryani (Single)", category: "Biryani", price: 229, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-special-full", name: "Special Chicken Biryani (Full)", category: "Biryani", price: 335, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-moghlai-single", name: "Moghlai Chicken Biryani (Single)", category: "Biryani", price: 199, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-moghlai-full", name: "Moghlai Chicken Biryani (Full)", category: "Biryani", price: 299, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-gongura-single", name: "Gongura Chicken Biryani (Single)", category: "Biryani", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-gongura-full", name: "Gongura Chicken Biryani (Full)", category: "Biryani", price: 319, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-prawns-single", name: "Prawns Biryani (Single)", category: "Biryani", price: 205, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-prawns-full", name: "Prawns Biryani (Full)", category: "Biryani", price: 349, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-65", name: "Chicken 65 Biryani", category: "Biryani", price: 169, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "biryani-chicken-roast", name: "Chicken Roast Biryani", category: "Biryani", price: 179, isVeg: false, available: true, discountPercent: 0, image: "" },

  // VEG BIRYANI (SINGLE / FULL)
  { id: "biryani-mushroom-single", name: "Mushroom Biryani (Single)", category: "Veg Biryani", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "biryani-mushroom-full", name: "Mushroom Biryani (Full)", category: "Veg Biryani", price: 249, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "biryani-paneer-single", name: "Paneer Biryani (Single)", category: "Veg Biryani", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "biryani-paneer-full", name: "Paneer Biryani (Full)", category: "Veg Biryani", price: 269, isVeg: true, available: true, discountPercent: 0, image: "" },

  // MOJITOS
  { id: "mojito-mint", name: "Mint Mojito", category: "Mojitos", price: 119, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "mojito-strawberry", name: "Strawberry Mojito", category: "Mojitos", price: 119, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "mojito-watermelon", name: "Watermelon Mojito", category: "Mojitos", price: 119, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "mojito-blueberry", name: "Blue Berry Mojito", category: "Mojitos", price: 119, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "mojito-greenapple", name: "Green Apple Mojito", category: "Mojitos", price: 119, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "mojito-kiwi", name: "Kiwi Mojito", category: "Mojitos", price: 119, isVeg: true, available: true, discountPercent: 0, image: "" },

  // NEWLY ADDED CATEGORIES
  { id: "signa-singapore-chicken", name: "Singapore Chicken", category: "Signature Chicken Specials", price: 345, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "signa-chicken-green-line", name: "Chicken Green Line", category: "Signature Chicken Specials", price: 285, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "signa-ginger-chicken", name: "Ginger Chicken", category: "Signature Chicken Specials", price: 229, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "signa-lemon-chicken", name: "Lemon Chicken", category: "Signature Chicken Specials", price: 229, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "signa-jawad-chicken", name: "Jawad Chicken", category: "Signature Chicken Specials", price: 239, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "signa-chef-special-chicken", name: "Chef Special Chicken", category: "Signature Chicken Specials", price: 399, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "signa-maestro-special-chicken", name: "Maestro Special Chicken", category: "Signature Chicken Specials", price: 435, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-chilly-fish", name: "Chilly Fish", category: "Fish & Prawns Starters", price: 275, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-apollo-fish", name: "Apollo Fish", category: "Fish & Prawns Starters", price: 275, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-fish-65", name: "Fish 65", category: "Fish & Prawns Starters", price: 285, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-lemon-pepper-fish", name: "Lemon Pepper Fish", category: "Fish & Prawns Starters", price: 299, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-fish-fingers", name: "Fish Fingers", category: "Fish & Prawns Starters", price: 285, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-chilly-prawns", name: "Chilly Prawns", category: "Fish & Prawns Starters", price: 319, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-pepper-prawns", name: "Pepper Prawns", category: "Fish & Prawns Starters", price: 335, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-loose-prawns", name: "Loose Prawns", category: "Fish & Prawns Starters", price: 335, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-reshmi-kebab-full", name: "Reshmi Kebab (Full)", category: "Kebabs & Tandoor", price: 459, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-reshmi-kebab-half", name: "Reshmi Kebab (Half)", category: "Kebabs & Tandoor", price: 239, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-grill-chicken-full", name: "Grill Chicken (Full)", category: "Kebabs & Tandoor", price: 665, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-grill-chicken-half", name: "Grill Chicken (Half)", category: "Kebabs & Tandoor", price: 335, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-malai-kebab-full", name: "Malai Kebab (Full)", category: "Kebabs & Tandoor", price: 399, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-malai-kebab-half", name: "Malai Kebab (Half)", category: "Kebabs & Tandoor", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-kalmi-kebab-full", name: "Kalmi Kebab (Full)", category: "Kebabs & Tandoor", price: 459, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-kalmi-kebab-half", name: "Kalmi Kebab (Half)", category: "Kebabs & Tandoor", price: 239, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-haryali-kebab-full", name: "Haryali Kebab (Full)", category: "Kebabs & Tandoor", price: 515, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-haryali-kebab-half", name: "Haryali Kebab (Half)", category: "Kebabs & Tandoor", price: 265, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-sheekh-kebab-full", name: "Sheekh Kebab (Full)", category: "Kebabs & Tandoor", price: 399, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-sheekh-kebab-half", name: "Sheekh Kebab (Half)", category: "Kebabs & Tandoor", price: 265, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-chicken-tikka-full", name: "Chicken Tikka (Full)", category: "Kebabs & Tandoor", price: 299, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-tangadi-kebab-full", name: "Tangadi Kebab (Full)", category: "Kebabs & Tandoor", price: 399, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-tandoori-fish-8-pc-full", name: "Tandoori Fish (8 Pc) (Full)", category: "Kebabs & Tandoor", price: 345, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-fish-tikka-8-pc-full", name: "Fish Tikka (8 Pc) (Full)", category: "Kebabs & Tandoor", price: 345, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-prawns-tandoori-full", name: "Prawns Tandoori (Full)", category: "Kebabs & Tandoor", price: 399, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "kebab-prawns-tikka-full", name: "Prawns Tikka (Full)", category: "Kebabs & Tandoor", price: 399, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "rotin-tandoori-roti", name: "Tandoori Roti", category: "🫓 Roti, Naan & Paratha", price: 15, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-butter-roti", name: "Butter Roti", category: "🫓 Roti, Naan & Paratha", price: 25, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-naan", name: "Naan", category: "🫓 Roti, Naan & Paratha", price: 30, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-pudina-naan", name: "Pudina Naan", category: "🫓 Roti, Naan & Paratha", price: 35, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-butter-naan", name: "Butter Naan", category: "🫓 Roti, Naan & Paratha", price: 45, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-garlic-naan", name: "Garlic Naan", category: "🫓 Roti, Naan & Paratha", price: 50, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-laccha-paratha", name: "Laccha Paratha", category: "🫓 Roti, Naan & Paratha", price: 55, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-methi-paratha", name: "Methi Paratha", category: "🫓 Roti, Naan & Paratha", price: 25, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-aloo-paratha", name: "Aloo Paratha", category: "🫓 Roti, Naan & Paratha", price: 45, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-paneer-paratha", name: "Paneer Paratha", category: "🫓 Roti, Naan & Paratha", price: 55, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-plain-kulcha", name: "Plain Kulcha", category: "🫓 Roti, Naan & Paratha", price: 35, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "rotin-basket-4", name: "Basket (4)", category: "🫓 Roti, Naan & Paratha", price: 120, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-dal", name: "Dal", category: "Veg Curries", price: 69, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-dal-tadka", name: "Dal Tadka", category: "Veg Curries", price: 95, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-butter-dal", name: "Butter Dal", category: "Veg Curries", price: 79, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-malai-dal", name: "Malai Dal", category: "Veg Curries", price: 89, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-mix-veg", name: "Mix Veg", category: "Veg Curries", price: 105, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-kadai-veg", name: "Kadai Veg", category: "Veg Curries", price: 125, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-singapore-veg", name: "Singapore Veg", category: "Veg Curries", price: 149, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-jaipuri", name: "Jaipuri", category: "Veg Curries", price: 149, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-paneer-butter-masala", name: "Paneer Butter Masala", category: "Veg Curries", price: 159, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-kadai-paneer", name: "Kadai Paneer", category: "Veg Curries", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-malai-paneer", name: "Malai Paneer", category: "Veg Curries", price: 159, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-kheema-paneer", name: "Kheema Paneer", category: "Veg Curries", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-methi-paneer", name: "Methi Paneer", category: "Veg Curries", price: 185, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-palak-paneer", name: "Palak Paneer", category: "Veg Curries", price: 159, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-maestro-paneer-special", name: "Maestro Paneer Special", category: "Veg Curries", price: 195, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-butter-palak-paneer", name: "Butter Palak Paneer", category: "Veg Curries", price: 159, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-palak", name: "Palak", category: "Veg Curries", price: 135, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-tomato", name: "Tomato", category: "Veg Curries", price: 135, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-aloo-tomato", name: "Aloo Tomato", category: "Veg Curries", price: 149, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-tomato-chutney", name: "Tomato Chutney", category: "Veg Curries", price: 135, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-aloo-palak", name: "Aloo Palak", category: "Veg Curries", price: 149, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-gobi-curry", name: "Gobi Curry", category: "Veg Curries", price: 135, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-gobi-masala", name: "Gobi Masala", category: "Veg Curries", price: 149, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-gobi-tomato", name: "Gobi Tomato", category: "Veg Curries", price: 135, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-kaju-tomato", name: "Kaju Tomato", category: "Veg Curries", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-ods-special-curry", name: "ODS Special Curry", category: "Veg Curries", price: 185, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-khandari-curry", name: "Khandari Curry", category: "Veg Curries", price: 195, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-mushroom-masala", name: "Mushroom Masala", category: "Veg Curries", price: 159, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-mushroom-curry", name: "Mushroom Curry", category: "Veg Curries", price: 159, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-baby-corn-masala", name: "Baby Corn Masala", category: "Veg Curries", price: 159, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "vegcu-crispy-corn-masala", name: "Crispy Corn Masala", category: "Veg Curries", price: 169, isVeg: true, available: true, discountPercent: 0, image: "" },
  { id: "chick-chicken-curry-5-pc", name: "Chicken Curry (5 Pc)", category: "Chicken Curries", price: 149, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-chicken-masala-5-pc", name: "Chicken Masala (5 Pc)", category: "Chicken Curries", price: 159, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-chicken-fry-6-pc", name: "Chicken Fry (6 Pc)", category: "Chicken Curries", price: 169, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-mughalai-chicken-bone", name: "Mughalai Chicken (Bone)", category: "Chicken Curries", price: 169, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-mughalai-chicken-boneless", name: "Mughalai Chicken (Boneless)", category: "Chicken Curries", price: 185, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-butter-chicken-boneless", name: "Butter Chicken (Boneless)", category: "Chicken Curries", price: 185, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-ginger-chicken-boneless", name: "Ginger Chicken (Boneless)", category: "Chicken Curries", price: 195, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-spicy-chicken-bone", name: "Spicy Chicken (Bone)", category: "Chicken Curries", price: 185, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-spicy-chicken-boneless", name: "Spicy Chicken (Boneless)", category: "Chicken Curries", price: 195, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-kadai-chicken-bone", name: "Kadai Chicken (Bone)", category: "Chicken Curries", price: 185, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-kadai-chicken-boneless", name: "Kadai Chicken (Boneless)", category: "Chicken Curries", price: 195, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-kadai-chilly-chicken-curry-bone", name: "Kadai Chilly Chicken Curry (Bone)", category: "Chicken Curries", price: 205, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-kadai-chilly-chicken-curry-boneless", name: "Kadai Chilly Chicken Curry (Boneless)", category: "Chicken Curries", price: 195, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-maestro-special-chicken-curry-bone", name: "Maestro Special Chicken Curry (Bone)", category: "Chicken Curries", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-maestro-special-chicken-curry-boneless", name: "Maestro Special Chicken Curry (Boneless)", category: "Chicken Curries", price: 229, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-ods-special-chicken", name: "ODS Special Chicken", category: "Chicken Curries", price: 219, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-chef-special-chicken", name: "Chef Special Chicken", category: "Chicken Curries", price: 239, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "chick-gongura-chicken-5-pc", name: "Gongura Chicken (5 Pc)", category: "Chicken Curries", price: 205, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "eggcu-egg-bhurji", name: "Egg Bhurji", category: "Egg Curries", price: 115, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "eggcu-egg-masala", name: "Egg Masala", category: "Egg Curries", price: 135, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "eggcu-egg-curry", name: "Egg Curry", category: "Egg Curries", price: 125, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "eggcu-egg-fry-curry", name: "Egg Fry Curry", category: "Egg Curries", price: 135, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "eggcu-egg-kheema-masala", name: "Egg Kheema Masala", category: "Egg Curries", price: 135, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "mutto-mutton-curry-6-pc", name: "Mutton Curry (6 Pc)", category: "Mutton Curries", price: 285, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "mutto-mutton-masala-6-pc", name: "Mutton Masala (6 Pc)", category: "Mutton Curries", price: 285, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "mutto-mutton-ginger-6-pc", name: "Mutton Ginger (6 Pc)", category: "Mutton Curries", price: 299, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "mutto-butter-mutton-masala-6-pc", name: "Butter Mutton Masala (6 Pc)", category: "Mutton Curries", price: 309, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "mutto-gongura-mutton-6-pc", name: "Gongura Mutton (6 Pc)", category: "Mutton Curries", price: 319, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-fish-curry-boneless", name: "Fish Curry (Boneless)", category: "Fish & Prawns Curries", price: 299, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-fish-masala-boneless", name: "Fish Masala (Boneless)", category: "Fish & Prawns Curries", price: 299, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-fish-ginger-boneless", name: "Fish Ginger (Boneless)", category: "Fish & Prawns Curries", price: 309, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-butter-fish-boneless", name: "Butter Fish (Boneless)", category: "Fish & Prawns Curries", price: 319, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-prawns-curry-8-pc", name: "Prawns Curry (8 Pc)", category: "Fish & Prawns Curries", price: 309, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-prawns-masala-8-pc", name: "Prawns Masala (8 Pc)", category: "Fish & Prawns Curries", price: 309, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-prawns-ginger-8-pc", name: "Prawns Ginger (8 Pc)", category: "Fish & Prawns Curries", price: 319, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-butter-prawns-8-pc", name: "Butter Prawns (8 Pc)", category: "Fish & Prawns Curries", price: 335, isVeg: false, available: true, discountPercent: 0, image: "" },
  { id: "fishp-special-mix-non-veg-curry", name: "Special Mix Non-Veg Curry", category: "Fish & Prawns Curries", price: 365, isVeg: false, available: true, discountPercent: 0, image: "" },
];

export const CATEGORIES = [
"Chinese Soups",
  "Veg Starters",
  "Non-Veg Starters",
  "Veg Rice",
  "Veg Noodles",
  "Non-Veg Rice",
  "Non-Veg Noodles",
  "Biryani",
  "Veg Biryani",
  "Mojitos",
  "Signature Chicken Specials",
  "Fish & Prawns Starters",
  "Kebabs & Tandoor",
  "🫓 Roti, Naan & Paratha",
  "Veg Curries",
  "Chicken Curries",
  "Egg Curries",
  "Mutton Curries",
  "Fish & Prawns Curries"
];

export function getLocalMenu() {
  const local = localStorage.getItem("maestro_menu_v2");
  if (local) {
    try {
      return JSON.parse(local);
    } catch (e) {
      console.error("Error parsing local menu, using default", e);
    }
  }
  return DEFAULT_MENU;
}

export function saveMenuToLocal(menu) {
  localStorage.setItem("maestro_menu_v2", JSON.stringify(menu));
}
